Brightspace/d2l-image-banner-overlay

bower.json, src/d2l-image-banner-overlay.html
This is for [US81136](https://rally1.rallydev.com/#/87829734000d/detail/userstory/85641725212). It requires [this LMS PR](https://git.dev.d2l/projects/CORE/repos/platformtools/pull-requests/1341/overview) in order to get the organization url.
Acceptance Criteria:
=> Add course name to overlay

src/d2l-image-banner-overlay.html
[US82411](https://rally1.rallydev.com/#/87829734000/detail/userstory/92371493252)
The `d2l-main-page-padding` values are percentage based which cause the margins of widgets on the homepage to expand/shrink as the viewport width changes (to a point; there is a media query at 615px that effectively creates a min-width of 15px). We want the side margins on the course name to flow in the same manner.
=> Make the course side margins scale with others on the page

src/d2l-image-banner-overlay.html
[US82413](https://rally1.rallydev.com/#/87829734000/detail/userstory/92371504628)
So daylight demo seems bizarrely inconsistent with regards to response times. It was determined that in cases of slow loading of the organization information it might be more palatable with a slower fade-in animation, as the existing .5s animation seemed to get lost (possibly just in the painting of the control or else because the white text is so stark against the background that your eyes don't notice the quick fade).
Regardless, the decision was made to increase the fade to 1.2s and then see how that feels.
=> slowed the animation for the overlay content to be a little less harsh

bower.json, src/d2l-image-banner-overlay.html
Ideally we can use these values to aid in understanding the perf impact of the overlay, as well as to judge changes to perf by new additions (presuming we add new relevant marks).
=> add perf marks

src/d2l-image-banner-overlay.html
[US82412](https://rally1.rallydev.com/#/87829734000/detail/userstory/92371496824)
**Problem**
Because IE, Edge, and FF do not support `-webkit-line-clamp` we cannot restrict the course name text to a max of 2 lines. As such, using the current method of sizing the gradient to grow or shrink with the text leads to an undesirable result when there are more then 2 lines of text (basically the entire image is lost behind the dark gradient).
**Acceptance Criteria**
For browsers that don't support `-webkit-line-clamp` (so IE, Edge, and FF) the gradient should be a static size, which is to say it should match the original mocks where it was optimized for a two-line course name (see attached).
=> Make the gradient a static size for non-webkit

src/d2l-image-banner-overlay.html, src/localize-behavior.html
Based off of https://github.com/Brightspace/d2l-image-banner-overlay/pull/12
Design:
http://2lu6ug.axshare.com/geography.html#Error=1&CSUM=1
Adds a spinner if the toggle takes a while, and an error message if it fails
To test the spinner:
- Go to network throttling in chrome
- Add a custom profile:
=> Add error alert

bower.json
The update of this on BSI failed because it couldn't find a good version for d2l-hm-behavior
https://github.com/Brightspace/brightspace-integration/pull/512
=> update version of organization-hm-behavior to be the correct one

src/d2l-image-banner-overlay-styles.html
Found this when fooling around in IE
The change-image animation changed how the loading spinner was hidden, so I needed to add one more selector for the "please wait as we remove your banner" spinner or it would never come out of hiding
=> Fix the loading spinner

bower.json, package.json, src/d2l-image-banner-overlay.html
Unfortunately, there is a bug in polylint (https://github.com/PolymerLabs/polylint/issues/141) that doesn't allow for URLs to be used directly... which is a pretty big deal. Removing polylint because of this - it has arguable benefits anyway.
=> US84675 - Remove d2l-siren-parser-ui

.eslintrc, bower.json, src/d2l-image-banner-overlay.html
Since we are eventually updating the overlay banner for the fix found in #21 I figured maybe this was a good chance to try out authify in a non-iFRA context. Which was great because it forced me to think through how this was going to be consumed (resulting in [d2l-authify-import](https://github.com/Brightspace/d2l-authify-import)) and also uncovered a bug (fixed [here](https://github.com/Brightspace/d2l-authify/pull/9) ).
Functionally nothing should change, we should still properly load the course name based on the fetch to the organizations api and toggle the banner on and off.
=> Replace d2l-ajax with d2l-authify

bower.json, src/d2l-image-banner-overlay.html
Discovered that if canonical namespaces were OFF the previous version of d2l-authify (0.2.0) did not send cookies so calls to relative urls would `403`. This bump implements the fix.
Acceptance Criteria:
- overlay should show correctly with canonical namespaces ON and OFF
- overlay toggle functionality (remove/undo) should work with canonical namespaces ON and OFF
- works in all browsers
TODO:
=> bump authify to fix 403s on non-canon calls to /organizations

src/d2l-image-banner-overlay-styles.html
..with 1 or 2 lines of text, and no darker to match design.
Went over this with Jeff to confirm exact values in various scenarios.  Seems to be good.  We originally decided to update this because the gradient looked a little too dark sometimes.  However, when doing that we also noticed that the default gradient (for browsers that do not support text clamping) was not accessible enough (not dark enough).
=> Updating linear gradients to always be accessible

bower.json
The `d2l-polymer-behaviors` dependency appears to not be used in this project.
=> Remove d2l-polymer-behaviors dependency since it is not used.

bower.json, src/d2l-image-banner-overlay.html
This passes along the new image upload callback to the image selector.  It also has a new focus function for the lms to call when it is done uploading a new course image, and a function "courseImageUploadCompleted" to also be called when done.
The image will be refreshed upon successful completion.  This means calling the API for the organization, getting the href for the image, and updating the images src.  This required appending a #datetimestamp to the end of the src link so that browsers wouldn't cache the image at that point.  I looked around online and this seemed to be the most reliable way to accomplish this across browsers, as even changing cache headers and stuff seemed to be inconsistently successful.
You'll see that the use of "_shouldRefreshCourseImage" is a bit awkward I …
=> Allow upload callback function to be provided

.travis.yml, bower.json, package.json, polymer.json, src/d2l-image-banner-overlay.html, wct.conf.json
These are more or less equivalent, but d2l-fetch is a more fleshed out approach, with middlewares and such. Note that this is a breaking change, as `d2l-image-banner-overlay` will now require the consumer to set up the appropriate middlewares; in particular, `d2l-fetch-auth` is required.
=> Switch to d2l-fetch from d2l-authify

src/d2l-image-banner-overlay.html, wct.conf.json
These events were renamed but were missed in the observers array.
Also, default to latest Safari on Sauce with an empty string.
=> DE28347 Fix event names

src/d2l-image-banner-overlay.html, test/d2l-image-banner-overlay.js
Previously, this was being accomplished by an event listener inside d2l-simple-overlay, but it was specific to this case. So, it will be removed from there, which means we have to explicitly close the overlay when a set-course-image event occurs.
(The change to `d2l-simple-overlay` to remove this behavior is in https://github.com/Brightspace/simple-overlay/pull/16, so this needs to merge + release before that merges + releases.)
See also https://github.com/Brightspace/d2l-my-courses-ui/pull/495.
=> Close overlay when image is changed

d2l-image-banner-overlay-styles.html
A few things that are prompting this change:
First, the way the CSS rule is written, it wasn't ever getting applied -- it needed `:host([selector])` with the brackets.
With shadow DOM enabled, the fact that it wasn't getting applied combined with the `:host` having a `z-index` of `1` was causing `simple-overlay` (which just uses `iron-overlay-behavior` under the covers) to appear beneath the backdrop, despite having a higher z-index relative to the backdrop. That's because while its z-index was higher than the backdrop's, it having a parent with a z-index of 1, plus shadow DOM, confuses the browser.
=> fixing simple-overlays being under the backdrop in Polymer 2

d2l-image-banner-overlay-styles.html
The issue here is that `opacity: 0` makes it invisible, but it still takes up physical space and is still visible to screen readers. Also caused a strange bug in IE11 where the "..." menu was always visible even when the banner was removed.
=> fully hiding the overlay content

d2l-image-banner-overlay.html
I based this on how the overflow menu was hidden in my courses, which I believe was based of d2l-menu a while ago.
https://github.com/Brightspace/d2l-my-courses-ui/blob/master/src/d2l-course-tile.html#L729
Tested Chrome/Firefox/Edge/Safari and Android/iOS and it works as expected.
=> Close the menu on blur

localize-behavior.html
Korean translation was moved into `ko` (was mistakenly placed in `nb`), and missing `nb` translation was taken from My Courses (same wording/context)
=> Fix translations
